config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  resources :posts do
    resources :comments
  end

  resources :networks

  get '/' => 'users#landing_page'

  get '/all_posts' => 'posts#all_posts'

  get '/networks/join/:id' => 'networks#join', as: 'join'

  get '/networks/leave/:id' => 'networks#leave', as: 'leave'

  get '/networks/:id/posts' => 'networks#show_network_posts', as: 'network_posts'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post 
end

app/models/network.rb
class Network < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :posts 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :pic, default_url: ""
  validates_attachment :pic, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  validates :post_title, :presence => true

  paginates_per 3
  has_many :comments
  belongs_to :user
  belongs_to :network
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_and_belongs_to_many :networks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(user)
        user_path(user)
    end


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(comment_params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.update(user_id: current_user.id)
    @comment.save

  redirect_to post
  end

  def new
  end

  def show
  end


private

  def comment_params
    params.require(:comment).permit(:comment_content, :comment_date, :user_id, :post_id)
  end
end

app/controllers/my_sessions_controller.rb
class MySessionsController < Devise::SessionsController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController

  def index
  end

  def new
    @network = Network.new
  end

  def create
    @network = Network.new(network_params)
    if @network.save
      flash[:notice] = 'Network created successfully!'
      current_user.networks.push(@network)
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = 'Network not created successfully. Please try again.'
      render 'create'
    end


  end

  def show
    @all_networks = Network.all
  end

  def show_network_posts
    @network = Network.find(params[:id])
    @posts = @network.posts.all
  end

  def join
    @user_networks = current_user.networks
    @network = Network.find(params[:id])

    unless @user_networks.include?(@network)
      current_user.networks.push(@network)
      flash[:notice] = 'Network added successfully'
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = 'You are already a member of this network'
      redirect_to user_path(current_user.id)
    end
  end

  def leave
    @network = Network.find(params[:id])
    if @user_networks.include?(@network)
      current_user.networks.delete(@network)
      flash[:notice] = 'You have successfully left the network'
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = 'You are not a member of this network'
      redirect_to user_path(current_user.id)
    end

  end

private

  def network_params
    params.require(:network).permit(:user_id, :network_name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def new
  end


  def create
    @post = Post.new(post_params)
    @post.update(user_id: current_user.id)


    if @post.save
      flash[:notice] = 'Your post has been saved successfully!'
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = 'Your post has not been saved. Please check the form and try again.'
      redirect_to user_path(current_user.id)
    end
    # binding.pry

  end

  def show
    @comment = Comment.new
    # @network = post.network.id
    @selected_post = Post.find_by(id: params[:id])
    @comments = @selected_post.comments
    @current_user_posts = Post.where(user_id: current_user.id)

  end

  def edit
    @post = Post.find_by(id: params[:id])
    # @post.update(post_content: params[:post_content])

  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = 'Post was updated successfully'
      redirect_to post_path(params[:id])
    else
      flash[:notice] = 'Post was not updated successfully'
      render edit_post_path(params[:id])
    end
  end

  def all_posts
    @posts = Post.all

  end

  def post_params
    params.require(:post).permit(:post_title, :post_date, :post_content, :user_id, :pic, :network_id)
  end
end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def landing_page
  end

  def new
  end

  def create
    @user = User.new(user_params)
    byebug
    if @user.save
      redirect_to user_path
    else
      redirect_to new_user_registration_path
    end
  end

  def sign_up
  end

  def show
    @all_networks = Network.all
    @user_networks = current_user.networks
    # @network_users = Network.where(id: current_user.network_id)
    @post = Post.new
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = 'You are not authorized to view this page'
      redirect_to '/'

    else
      @posts = Post.all
      # @posts = Post.where(user_id: @user.id).page(1)
      render 'show'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/my_sessions_helper.rb
module MySessionsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article class="comment"><%= comment.comment_content %><br >
Posted By: <%= User.find(comment.user_id).first_name %> <%= User.find(comment.user_id).last_name %>, <%= Time.now.strftime("%A %d %B %Y") %><br >  </article><br>

app/views/layouts/_messages.html.erb
<div id="notice">
  <% flash.each do |key, msg| %>
    <div class="alert-temp alert fade in alert-<%= key %>"><%= msg %></div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" style="margin:0px; border-radius:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Travel:On</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", user_path(current_user.id) %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Create Network', new_network_path %></li>
        <li><%= link_to 'Join Network', network_path(current_user.id) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Networks <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% current_user.networks.each do |user_network| %>
              <li>

                    <%= link_to user_network.network_name, network_posts_path(user_network) %>
              </li>
            <%end%>
          </ul>
        </li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternationalApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"%>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <% if current_user %>
        <%= render 'layouts/navigation' %>
      <% end %>

    </header>
    <main role="main">
      <%= render 'layouts/messages' %>


      <%= yield %>
    </main>



  </body>
</html>

app/views/networks/new.html.erb
<div class="container-fluid create_network_container">
  <h3><strong>Create a Network</strong></h3>

  <%= form_for @network do |f| %>
    <div class="field">
      <strong><%= f.label :network_name %></strong><br />
      <%= f.text_field :network_name%>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="actions create_network_button">
      <%= f.submit "Create" %>
    </div>
  <%end%>
  <div class="cancel_link">
    <%= link_to 'Cancel', user_path(current_user.id), method: 'GET', class: "btn btn-info" %>
  </div>
</div>

app/views/networks/show.html.erb
<div class="container-fluid join_network_container">
  <div class="row">
    <div class="col-sm-4">

    </div>
    <div class="col-sm-4">
      <div class="text-center">
        <h4><strong>Please select a network to join</strong></h4>
        <% @all_networks.each do |network| %>
        <div class="text-center list_of_networks">
          <p><%= link_to network.network_name, join_path(network.id)%></p>
        </div>
        <%end%>
      </div>
    </div>
    <div class="col-sm-4">

    </div>
  </div>

</div>

app/views/networks/show_network_posts.html.erb
<div class="container-fluid network_posts_container">
  <div class="text-center">
    <strong><h3>List of Posts</h3>
    <% @posts.each do |post| %>
      <p>Post Title: <%= link_to post.post_title, post_path(post)%></p>
      <p>Network: <%= post.network.network_name %></p>
      <p>Date Posted: <%= post.post_date.strftime("%A %d %B %Y") %></p>
      <p>Posted By: <%= post.user.first_name %> <%= post.user.last_name %></p><br>
    <%end%></strong>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid edit_post_container">
  <%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :post_title %><br />
      <%= f.text_field :post_title%>
    </div>

    <div class="field">
      <%= f.label :post_content %><br />
      <%= f.text_field :post_content%>
    </div>

    <div>
      <%= f.label :pic %>
      <%= f.file_field :pic %>
    </div><br>

      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :post_date, :value => Time.now.strftime("%A %d %B %Y") %>

    <div class="actions">
      <%= f.submit "Post" %>
    </div><br>
  <% end %>
  <%= link_to "Cancel", post_path(params[:id]), class: "btn btn-info" %>
</div>

app/views/posts/show.html.erb
<div class="container-fluid post_details_container"><br>
  <%= link_to 'Back', network_posts_path(@selected_post.network_id), method: 'GET', class: "btn btn-info" %><br>

  <div class="panel panel-primary content_panel">
    <div class="panel-heading">
      <h3 class="panel-title"><strong>Post Title:</strong> <%= @selected_post.post_title %></h3>
    </div>
    <div class="panel-body">
      <strong>Post Content:</strong> <%= @selected_post.post_content %>
    </div>
    <div class="panel-footer"><strong>Network:</strong> <%= @selected_post.network.network_name  %></div>
  </div>
  <div class="image">
    <%= image_tag @selected_post.pic.url, width: '100' %>
  </div>



  <div class="panel panel-info content_panel">
    <div class="panel-heading">
      <h3 class="panel-title"><h3>Comments</h3></h3>
    </div>
    <div class="panel-body">
      <%= render @comments %>
    </div>
  </div>


  <% if @current_user_posts.find { |post| post.id == @selected_post.id}  %>
   <%= link_to "edit post", edit_post_path, class: "btn btn-info" %>
    <%end%>

  <%= form_for [@selected_post, @comment] do |f| %>
    <div class="field">
      <%= f.label :Comment %><br />
      <%= f.text_field :comment_content %>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :comment_date, :value => Time.now.strftime("%A %d %B %Y") %>
    <%= f.hidden_field :post_id, :value => @selected_post.id %>

    <div class="actions btn">
      <%= f.submit "Post" %>
    </div>
  <%end%>

</div>

app/views/users/landing_page.html.erb
<div class="container-fluid landing_page_container">
  <div class="row">
    <div class="col-sm-8">
    </div>
    <div class="col-sm-2">
      <a class="btn btn-primary pull-right" href="/users/sign_in">Sign In</a>
    </div>
    <div class="col-sm-2">
      <a class="btn btn-primary pull-left" href="/users/sign_up">Sign Up</a>
    </div>
  </div>

  <div class="row">
    <h1><p class="text-center">
      Travel:On
    </p></h1>
  </div>

  <div class="row">
    <h3><p class="text-center">
      No matter where you are in the world, you are never more than a click away from home.

    </p></h3>
  </div>

  <div class="row">
  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="/stylesheets/show.css" >
    <meta charset="utf-8">
    <title>Main Page</title>
  </head>
  <body>
    <div class="container-fluid homepage_container">
      <div class="row">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-3">
        </div>
        <div class="col-sm-3">
        </div>
        <div class="col-sm-3">
        </div>
      </div>

      <div class="row">
        <div class="col-sm-5">
          <div class="text-left">
            <% if user_signed_in? %>
            <div class="welcome_name">
              <h2><strong>Welcome <%= @user.first_name %>!</strong></h2>
            </div>
            <%end%>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="text-left">
            <div class="today_and_networks_text">
              <h4>Today is...</h4>
            </div>
            <div class="today">
              <h5><%= Time.now.strftime("%A %d %B %Y") %></h5>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-5">
          <%= form_for @post do |f| %>
            <div class="field">
              <div class="post_form">
                <strong><%= f.label :post_title %></strong><br />
              </div>
              <%= f.text_field :post_title%>
            </div>
            <div class="field">
              <div class="post_form">
                <strong><%= f.label :post_content %></strong><br />
              </div>
              <%= f.text_field :post_content%>
            </div>
            <div>
              <div class="post_form">
                <strong><%= f.label :Network %></strong>
              </div>
              <%= f.collection_select(:network_id, @user_networks, :id, :network_name) %>
            </div>
            <div>
              <div class="post_form">
                <%= f.label :photo %>
              </div>
              <%= f.file_field :pic %>
            </div>

              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :post_date, :value => Time.now.strftime("%A %d %B %Y") %>

            <div class="actions btn">
              <%= f.submit "Post" %>
            </div>
          <% end %>
        </div>
        <div class="col-sm-4">
          <div class="text-left">
            <div class="today_and_networks_text">
              <h4>My Networks:</h4>
            </div>
            <% @user_networks.each do |user_network| %>
            <div class="network_list">
              <ol>
                <h5><%= link_to user_network.network_name, network_posts_path(user_network) %> </h5>
              </ol>
            </div>
            <%end%>
          </div>
        </div>
        <div class="col-sm-4">
        </div>
      </div>
    </div>
  </body>
</html>